-- 진단 요청 빈도 제한 전용 테이블.
--
-- Submission 행을 기준으로 빈도를 세면, "판별 실패 시 미저장" 정책 때문에
-- 실패한 요청이 행을 남기지 않아 제한을 전부 빠져나간다.
-- 비용을 발생시키는 요청만 정확히 제한을 통과하는 셈이 되므로,
-- 성공 실패와 무관하게 남는 "시도" 를 별도로 기록한다.
--
-- (pet_id, type) 당 한 행만 유지한다. 갱신만 하므로 테이블이 자라지 않는다.
CREATE TABLE diagnosis_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    last_attempted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_diagnosis_attempts_pet
        FOREIGN KEY (pet_id)
        REFERENCES pets(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_diagnosis_attempts_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_diagnosis_attempts_pet_type UNIQUE (pet_id, type)
);

CREATE INDEX idx_diagnosis_attempts_user_id
    ON diagnosis_attempts (user_id);

CREATE INDEX idx_diagnosis_attempts_last_attempted_at
    ON diagnosis_attempts (last_attempted_at);
