-- =========================================================
-- V54: 진단 요청 "시도" 기록 테이블
--
-- 건강검진표 OCR 등록(HEALTH-01)은 인식에 실패하면 submissions 행을
-- 만들지 않는다. 따라서 기존처럼 가장 최근 submissions 행으로 빈도를
-- 제한하면, 유료 OCR 호출을 발생시키고 실패한 요청만 정확히 제한을
-- 빠져나간다. 성공·실패와 무관하게 남는 "시도"를 세기 위한 테이블이다.
-- =========================================================

CREATE TABLE diagnosis_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    attempted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_diagnosis_attempts_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_diagnosis_attempts_user_id_type_attempted_at
    ON diagnosis_attempts (user_id, type, attempted_at);
