-- 건강검진표(진단서) OCR 결과 기록.
--
-- 이미지 키 컬럼이 없다. 원본 이미지는 submissions.photo_url 에 있다.
-- raw_ocr_json 컬럼도 두지 않는다 — OCR 원응답에는 견주 성명 주소가 포함되며,
-- 화이트리스트한 12개 항목만 꺼내 저장한다.
CREATE TABLE pet_health_certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    submission_id UUID NOT NULL,

    -- 진단서 12개 항목.
    -- 종류 성별 연령을 enum 이 아니라 원문으로 두는 이유:
    -- 진단서는 'Canine' / 'Castrated Male' / '16년 3개월' 처럼 적으며,
    -- PetSpecies PetGender 로 변환하면 중성화 여부와 개월 단위 나이가 손실된다.
    animal_name         VARCHAR(255),   -- 동물명
    species_text        VARCHAR(255),   -- 종류 (원문)
    breed               VARCHAR(255),   -- 품종
    gender_text         VARCHAR(255),   -- 성별 (원문)
    coat_color          VARCHAR(255),   -- 모색
    age_text            VARCHAR(255),   -- 연령 (원문)
    features            TEXT,           -- 특징
    disease_name        TEXT NOT NULL,  -- 병명 (필수)
    onset_date          DATE,           -- 발병 연원일 (파싱 성공 시)
    onset_date_text     VARCHAR(64),    -- 발병 연원일 (원문)
    diagnosed_date      DATE,           -- 진단 연원일 (파싱 성공 시)
    diagnosed_date_text VARCHAR(64) NOT NULL,  -- 진단 연원일 (원문, 필수)
    prognosis           TEXT,           -- 예후 소견
    remarks             TEXT,           -- 그외의 사항 (비고)

    ocr_confidence NUMERIC(5,4) NOT NULL,
    is_manually_edited BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_pet_health_certificates_pet
        FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE,

    CONSTRAINT fk_pet_health_certificates_submission
        FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,

    -- 제출 1건당 진단서 1건을 보장한다.
    CONSTRAINT uq_pet_health_certificates_submission UNIQUE (submission_id),

    CONSTRAINT chk_pet_health_certificates_ocr_confidence
        CHECK (ocr_confidence >= 0 AND ocr_confidence <= 1)
);

CREATE INDEX idx_pet_health_certificates_pet_id
    ON pet_health_certificates (pet_id);

CREATE INDEX idx_pet_health_certificates_diagnosed_date
    ON pet_health_certificates (diagnosed_date);
